### ISSUE TITLE
getVersion should only be called if a valid Instana URL has been configured

### ISSUE THREAD

**Issue by d0ugal** [instana/instana-grafana-datasource#107]
Every time I go to create a new Instana datasource this error pops up.

![2022-06-07T16:35:31,036305842+01:00](https://user-images.githubusercontent.com/48211/172422027-61a18a87-fb58-429f-8043-ad244cc42e3f.png)

Looking in my dev tools I can see a request is being made to `https://HOSTNAME/undefined/api/instana/version`

I suspect this is because`options.url` isn't set here yet. https://github.com/instana/instana-grafana-datasource/blob/6c4b6db927f93581c9a2d6ee2ca3dbe42143904f/src/util/request_handler.ts#L9

**Comment by Sarathsgck12** [comment]
The issue will be resolved as part of the new V4.0.0
