### ISSUE TITLE
Upgrade to Grafana v 10.x+ seems to break the edit mode for Panels with the Instana Datasource

### ISSUE THREAD

**Issue by Daniel-Ebert** [instana/instana-grafana-datasource#114]
Hi there,

when upgrading to Grafana v10x+, the creation of a Panel with the Instana Datasource still works as before. 
The Panel is also shown correctly in the "viewer"-Mode of a Dashboard:
![grafik](https://github.com/instana/instana-grafana-datasource/assets/6033570/4f3f61d8-6cdc-4178-b5c0-947a644f5b9d)

Although, after saving, reloading the page and then opening the "edit"-View of one panel, the values in the selectable fields are not prefilled anymore and the panel data is not rendered correctly. 
If I now hit save, it breaks the configuration of the panel:
![grafik](https://github.com/instana/instana-grafana-datasource/assets/6033570/483aea0d-c7c1-4e4d-95d7-197947e57f78)
Potentially, this only happens with custom metrics, but I'm not 100% sure. Maybe you can try to replicate the issue.

EDIT: Another thing that seems to be broken with Grafana 10 is the proxy mode in the Instana plugin settings

Plugin Version: Latest
Grafana Version: Grafana v10.0.1 (5a30620b85)

Best regards

Daniel

**Comment by Sarathsgck12** [comment]
The issue will be resolved as part of the new V4.0.0

**Comment by Sarathsgck12** [comment]
The issue will be resolved as part of the new V4.0.0
