### ISSUE TITLE
Call count (total) only consistent when rollup=1000

### ISSUE THREAD

**Issue by julia-leyton** [instana/instana-grafana-datasource#3]
**Instana datasource version:** 1.0.1

**Expected result:** Singlestat widget displaying Call Count (Total) for a WebService

**Result:** Total calls for a period of time only works if queries use rollup=1000

**Example:**

- Last 5 minutes (rollup 1000)
![screen shot 2018-04-09 at 15 48 46](https://user-images.githubusercontent.com/32554329/38516981-ecf3a41e-3c0e-11e8-9d4c-e951b910a1eb.png)

- Last 30 minutes (rollup 5000)
![screen shot 2018-04-09 at 15 49 06](https://user-images.githubusercontent.com/32554329/38516991-f2b5b838-3c0e-11e8-9347-257b2fac4401.png)

- Last 6 hours (rollup 60000)
![screen shot 2018-04-09 at 15 49 18](https://user-images.githubusercontent.com/32554329/38516996-f8565e64-3c0e-11e8-83cc-76820df22b71.png)

I think there's a factor missing (for rollup=1000 the factor is 1 so it is still consistent)

When multiplying the other results for the number of seconds: (385x5) and (360x60) the results are consistent.

Could you please check this? Thanks in advance!

Julia

**Comment by JeroenSoeters** [comment]
Hi Julia,

Can you please check how the dashboard is configured? In the options tab of the SingleStat widget you can specify an aggregation function under "Stat" (the first option). Can you verify that this is set to "Total" and possible make a screenshot of your dashboard configuration? It looks like it's displaying an average instead of a total.

- Jeroen

**Comment by julia-leyton** [comment]
Hi Jeroen,

Sure, I just checked and it is set to total. 

Here the screenshots and also the json(as txt, I only replaced the entityQuery value), please let me know if i'm missing something

[Pruebas Datasource-1523408514396.txt](https://github.com/instana/instana-grafana-datasource/files/1896938/Pruebas.Datasource-1523408514396.txt)
![screen shot 2018-04-10 at 22 00 04](https://user-images.githubusercontent.com/32554329/38591632-fc4019d4-3d0d-11e8-8ceb-cb02915fd13b.png)
![screen shot 2018-04-10 at 22 00 50](https://user-images.githubusercontent.com/32554329/38591635-fe035812-3d0d-11e8-82d8-c7663dc6c34b.png)
![screen shot 2018-04-10 at 22 01 24](https://user-images.githubusercontent.com/32554329/38591639-ffcc0810-3d0d-11e8-83cb-d60d07029bf0.png)

I also tried with other tenants and observed the same behaviour.

Best!
Julia

**Comment by JeroenSoeters** [comment]
Thanks for this info, I will investigate and get back to you.

Jeroen

**Comment by julia-leyton** [comment]
This was fixed in 1.0.2 
Thanks again!
