### ISSUE TITLE
Broken metrics

### ISSUE THREAD

**Issue by TorgeH** [instana/instana-grafana-datasource#4]
Hi There
Whenever I leave the metric-editor in a state where it cannot display a metric (error or incomplete)

![image](https://user-images.githubusercontent.com/12459835/39364171-5be33cb4-4a2d-11e8-9d5f-5d9d2aa3b86f.png)
The Metric in question cannot be edited or removed anymore. The only solution is to remove the panel containing the broken metric.
Please check

**Comment by schmidtl** [comment]
Hey Torge,
thanks for your feedback & sorry for not responding earlier :(
It seems "meanwhile" the issue was resolved. Please try out our newest release.
/Lars
