### ISSUE TITLE
the latest version doesn't seem to work (2.7.1) 

### ISSUE THREAD

**Issue by kadzu** [instana/instana-grafana-datasource#72]
Hi there,

I'm not sure but a prefer to notify this as an Issue.

I noticed that last version has new field (call entity) into the category "Analyze Applications Calls"

Src - Dest (filters & group by). I don't why, but my metrics are receiving 504 HTTP CODE (without graphs).

This is ok? 

Thanks.

**Comment by kadzu** [comment]
![image](https://user-images.githubusercontent.com/8013414/81223765-8e269580-8fb4-11ea-9b71-2fa16a318c11.png)
![image](https://user-images.githubusercontent.com/8013414/81223794-98e12a80-8fb4-11ea-82af-e0a3bcf70c5c.png)

**Comment by kadzu** [comment]
![image](https://user-images.githubusercontent.com/8013414/81223820-a8f90a00-8fb4-11ea-8f85-ea6bda98887c.png)

**Comment by Dalje-et** [comment]
Hi Sebastián,

thanks for opening this issue. Could you let me know what timeframe you are using? 

Thanks

**Comment by dsg-anthony** [comment]
I am also seeing this same issue, my timeframe is 5 minutes.

**Comment by schmidtl** [comment]
Hi Sebastián, hi Anthony,
this should be fixed with the new release 2.7.2 which is in review right now:
https://github.com/grafana/grafana-plugin-repository/pull/618
Best regards
/Lars

**Comment by schmidtl** [comment]
Hi Sebastián, hi Anthony,
the new release 2.7.2 is available now.
Best regards
/Lars

**Comment by kadzu** [comment]
Thanks a lot!!
