### ISSUE TITLE
Treat field "API token" as password in "Data Sources/Settings"

### ISSUE THREAD

**Issue by ppuschmann** [instana/instana-grafana-datasource#74]
I think it is interesting to have the field "API Token" in the settings of a Instana Data Source configured as password-field to prevent copying and reuse of the Token.

Of course this applies:
* The Token is already visible in plain on the Instana-Server given you have the correct role
* The Token only should have minimal permissions

**Comment by Dalje-et** [comment]
Hi,

We changed the input field to be of type "password" with the latest release (v.3.0.1). I will close this issue now.
